### ISSUE TITLE
Add software discussions to meeting agenda with link to KanBan board

### ISSUE THREAD

**Issue by jcmolloy** [ContentMine/site#368]

**Comment by tarrow** [comment]
So I've linked a load of repos to ContentMine/canary.

Can I unlink: old_site, workshops, workshop resources? We're they linked for any particular reason?

**Comment by jcmolloy** [comment]
It seems the linking is by organisation not repo - so the board you see in canary will be the same as the one you see in workshops and old_site. In that case we need to keep them all linked and you'll have to adjust the display to all repos and untick the ones you don't want to see them (not sure if it saves preferences!).

**Comment by tarrow** [comment]
Do you think they might be linked because they were already linked? For example I have linking in repositories from tarrow/... without any problems. Is it worth trying to unlink the admin stuff from the software and seeing what happens? I just don't want to break any workflows that you are all using effectively.

**Comment by jcmolloy** [comment]
Completed by @tarrow
